/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v2/companies/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Company Paths
         * @description Returns connection paths to a company. Returns up to 50 people at the company with up to 10 introducers per person.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompanyPathsRequest"];
                };
            };
            responses: {
                /** @description Company paths found successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CompanyPathsResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Bad request - invalid company identifier */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Company not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/companies/paths/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Check Company Paths
         * @description Quickly check if introduction paths exist to a company. Returns the warmth score and connector avatars (facepile) without full path details. Use this for previews or to determine if a full paths query is worthwhile.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CompanyPathsRequest"];
                };
            };
            responses: {
                /** @description Company check completed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CompanyCheckResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Bad request - invalid company identifier */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - missing or invalid authentication */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Authorization
         * @description Generate a token for a user. The token can be used to authenticate subsequent API requests on behalf of the user.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateTokenRequest"];
                };
            };
            responses: {
                /** @description Token created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["TokenResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Bad request - invalid request body */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - missing or invalid secret-key header */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Validation error - invalid external_user_id or email format */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/auth/tokens/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke Token
         * @description Revoke the current Bearer token. After revocation, the token can no longer be used for API requests. The user can obtain a new token by calling POST /v2/auth/tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token revoked successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["RevokeTokenResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Bad request - token missing jti claim */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User
         * @description Returns basic information and status for the currently authenticated user.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User information retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UserMeResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description User not found in the partner app */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/user/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel User Subscription
         * @description Cancel the subscription for the currently authenticated user. All existing tokens for this user will become invalid. The user can be reactivated by calling POST /v2/auth/tokens.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User subscription cancelled successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["CancelUserResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/integrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Gmail Integrations
         * @description Returns all Gmail integrations for the authenticated user with their settings and status.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Integrations retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["ListIntegrationsResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * Create Gmail Integration
         * @description Creates a new Gmail integration for mailbox functionality. This endpoint bypasses the OAuth flow and directly creates an integration with provided credentials.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        google_integration_properties: {
                            /**
                             * @description Google account identifier
                             * @example go:123456789
                             */
                            account_identifier: string;
                            /**
                             * Format: email
                             * @description Gmail address
                             * @example user@gmail.com
                             */
                            email: string;
                            authentication_token_data: {
                                /** @description Google OAuth access token */
                                access_token: string;
                                /** @description Google OAuth refresh token */
                                refresh_token?: string;
                                /** @description OAuth scopes granted */
                                scope: string;
                            };
                            /**
                             * @description Integration type
                             * @enum {string}
                             */
                            type: "google";
                            /**
                             * @description Data scopes for the integration
                             * @example [
                             *       "email",
                             *       "contacts"
                             *     ]
                             */
                            data_scope: string[];
                            /**
                             * @description Must be true for Gmail integration
                             * @enum {boolean}
                             */
                            authorized_gmail: true;
                            sync_data: {
                                /**
                                 * Format: email
                                 * @description Email address for sync data
                                 */
                                email: string;
                            };
                        };
                    };
                };
            };
            responses: {
                /** @description Integration created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["IntegrationResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Bad Request - Invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                                details?: {
                                    field: string;
                                    message: string;
                                }[];
                            };
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden - plan limits exceeded or insufficient permissions */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Conflict - integration already exists for this account */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/integrations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Gmail Integration
         * @description Updates settings for an existing Gmail integration including rate limits, status, and default flag.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /**
                     * @description Integration ID
                     * @example 123
                     */
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Daily email sending limit
                         * @example 50
                         */
                        email_sending_per_day?: number;
                        /**
                         * @description Hourly email sending limit
                         * @example 20
                         */
                        email_sending_per_hour?: number;
                        /**
                         * @description Minimum delay between emails in seconds
                         * @example 600
                         */
                        email_sending_min_delay_seconds?: number;
                        /**
                         * @description Timezone for scheduling
                         * @example America/New_York
                         */
                        timezone?: string;
                        /**
                         * @description Integration status
                         * @example connected
                         * @enum {string}
                         */
                        status?: "connected" | "disconnected" | "failed";
                        /**
                         * @description Whether this should be the default integration for email sending
                         * @example false
                         */
                        email_sending_default?: boolean;
                    };
                };
            };
            responses: {
                /** @description Integration updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["UpdateIntegrationResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Bad Request - Invalid input data or business rule violation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: {
                                code: string;
                                message: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found - integration not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Internal Server Error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/v2/app": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get App Information
         * @description Returns the partner application information for the authenticated token.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description App information retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["AppResponse"];
                            metadata: {
                                request_id: string;
                            };
                        };
                    };
                };
                /** @description Unauthorized - missing or invalid Bearer token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Basic company information */
        CompanyInfo: {
            name: string;
            domain: string;
            linkedin_url: string;
            village_url: string;
        };
        /** @description Connection strength summary with optional description */
        PathSummary: {
            score?: number;
            score_label?: string;
            description?: string;
        };
        /** @description Target person information */
        Target: {
            avatar?: string;
            first_name: string;
            last_name: string;
            full_name: string;
            id: string;
            identity_id: string;
            linkedin_identifier?: string;
            linkedin_url?: string;
            title?: string | null;
            village_person_url?: string;
        };
        /** @description Basic profile information for a person in a path */
        Profile: {
            first_name: string;
            last_name: string;
            linkedin_url: string;
            headline: string;
        };
        /** @description Relationship metadata explaining connection strength */
        ScoreMeta: {
            title: string;
            description: string;
        };
        /** @description Person who can initiate the introduction request */
        PathStarter: {
            profile: components["schemas"]["Profile"];
            score: number;
            score_label: string;
            score_description: string;
            score_meta: components["schemas"]["ScoreMeta"][];
        };
        /** @description Person who can make the introduction to the target */
        PathIntroducer: {
            profile: components["schemas"]["Profile"];
            score: number;
            score_label: string;
            score_meta: components["schemas"]["ScoreMeta"][];
        };
        /** @description Introduction path through mutual connections */
        IntroPath: {
            /** @enum {string} */
            type: "intro";
            summary: components["schemas"]["PathSummary"];
            starters: components["schemas"]["PathStarter"][];
            introducer: components["schemas"]["PathIntroducer"];
        };
        /** @description Direct connection to the target person */
        DirectPath: {
            /** @enum {string} */
            type: "direct";
            summary: components["schemas"]["PathSummary"];
            score_meta: components["schemas"]["ScoreMeta"][];
        };
        /** @description Connection path to target (either direct or via introduction) */
        Path: components["schemas"]["IntroPath"] | components["schemas"]["DirectPath"];
        /** @description Person at the target company with connection path info */
        TargetPerson: {
            target: components["schemas"]["Target"];
            paths: components["schemas"]["Path"][];
            summary: components["schemas"]["PathSummary"];
            count: number;
        };
        /** @description Company paths response with connection information */
        CompanyPathsResponse: {
            company: components["schemas"]["CompanyInfo"];
            summary: components["schemas"]["PathSummary"];
            target_people: components["schemas"]["TargetPerson"][];
            count: number;
        };
        /** @description Company identifier - provide one of: domain, linkedin_url, or url */
        CompanyPathsRequest: {
            /**
             * @description Company domain (normalized, without www prefix)
             * @example acme.com
             */
            domain: string;
        } | {
            /**
             * @description LinkedIn company page URL
             * @example https://linkedin.com/company/acme-corp
             */
            linkedin_url: string;
        } | {
            url: string;
        };
        /** @description Quick check for company connection paths */
        CompanyCheckResponse: {
            /** @description Whether any introduction paths exist */
            has_paths: boolean;
            /** @description Warmth score (0-100), null if no paths */
            score: number | null;
            /** @description Human-readable score label (e.g., "Strong", "Warm") */
            score_label: string | null;
            /** @description Number of people with paths at this company */
            count: number;
            /** @description Facepile avatar URLs (max 10) */
            avatars: string[];
        };
        /** @description Authentication token response */
        TokenResponse: {
            /**
             * @description JWT access token for API requests
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            token: string;
            /**
             * @description Token lifetime in seconds
             * @example 31536000
             */
            expires_in: number;
            /**
             * @description Unix timestamp when token expires
             * @example 1764739200
             */
            expires_at: number;
            /**
             * @description Token type (always Bearer)
             * @example Bearer
             * @enum {string}
             */
            token_type: "Bearer";
        };
        /** @description Request body for creating an authentication token */
        CreateTokenRequest: {
            /**
             * @description Unique identifier for the user in your system
             * @example user_123
             */
            external_user_id: string;
            /**
             * Format: email
             * @description Email address of the user
             * @example user@example.com
             */
            email: string;
        };
        /** @description Token revocation response */
        RevokeTokenResponse: {
            /**
             * @description Success message
             * @example Token revoked successfully
             */
            message: string;
        };
        /** @description Current authenticated user information */
        UserMeResponse: {
            /**
             * @description External user identifier provided by the partner application
             * @example user_abc123
             */
            id: string;
            /**
             * Format: email
             * @description User email address
             * @example john@example.com
             */
            email: string;
            /**
             * @description User full name
             * @example John Doe
             */
            name: string;
            /**
             * Format: date-time
             * @description Account creation timestamp in ISO 8601 format
             * @example 2024-01-01T00:00:00.000Z
             */
            created_at: string;
            /**
             * @description Whether the user has completed syncing their network data
             * @example true
             */
            is_sync_complete: boolean;
            /**
             * @description Whether the user is active in the partner application
             * @example true
             */
            is_active: boolean;
        };
        /** @description User subscription cancellation response */
        CancelUserResponse: {
            /**
             * @description Success message
             * @example User subscription cancelled successfully
             */
            message: string;
            /**
             * @description External user identifier that was cancelled
             * @example user_abc123
             */
            external_user_id: string;
        };
        /** @description Gmail integrations list response */
        ListIntegrationsResponse: {
            /** @description List of Gmail integrations */
            integrations: {
                /**
                 * @description Integration ID
                 * @example 123
                 */
                id: number;
                /**
                 * @description Integration type
                 * @example gmail
                 */
                type: string;
                /**
                 * @description Account identifier (email address)
                 * @example user@gmail.com
                 */
                account_identifier: string;
                /**
                 * @description Integration status
                 * @example connected
                 * @enum {string}
                 */
                status: "connected" | "disconnected" | "failed";
                /**
                 * @description Daily email sending limit
                 * @example 50
                 */
                email_sending_per_day: number;
                /**
                 * @description Hourly email sending limit
                 * @example 20
                 */
                email_sending_per_hour: number;
                /**
                 * @description Minimum delay between emails in seconds
                 * @example 600
                 */
                email_sending_min_delay_seconds: number;
                /**
                 * @description Timezone for scheduling
                 * @example America/New_York
                 */
                timezone: string;
                /**
                 * @description Whether Gmail is authorized
                 * @example true
                 */
                authorized_gmail: boolean;
                /**
                 * @description Token expiry date
                 * @example 2024-12-31T23:59:59Z
                 */
                token_expiry_date: string | null;
                /**
                 * @description Whether this is the default integration for email sending
                 * @example true
                 */
                email_sending_default: boolean;
                /**
                 * @description Whether refresh token is available
                 * @example true
                 */
                refresh_token_exists: boolean;
            }[];
            /** @description Default integration (if any) */
            default_integration: {
                /**
                 * @description Integration ID
                 * @example 123
                 */
                id: number;
                /**
                 * @description Integration type
                 * @example gmail
                 */
                type: string;
                /**
                 * @description Account identifier (email address)
                 * @example user@gmail.com
                 */
                account_identifier: string;
                /**
                 * @description Integration status
                 * @example connected
                 * @enum {string}
                 */
                status: "connected" | "disconnected" | "failed";
                /**
                 * @description Daily email sending limit
                 * @example 50
                 */
                email_sending_per_day: number;
                /**
                 * @description Hourly email sending limit
                 * @example 20
                 */
                email_sending_per_hour: number;
                /**
                 * @description Minimum delay between emails in seconds
                 * @example 600
                 */
                email_sending_min_delay_seconds: number;
                /**
                 * @description Timezone for scheduling
                 * @example America/New_York
                 */
                timezone: string;
                /**
                 * @description Whether Gmail is authorized
                 * @example true
                 */
                authorized_gmail: boolean;
                /**
                 * @description Token expiry date
                 * @example 2024-12-31T23:59:59Z
                 */
                token_expiry_date: string | null;
                /**
                 * @description Whether this is the default integration for email sending
                 * @example true
                 */
                email_sending_default: boolean;
                /**
                 * @description Whether refresh token is available
                 * @example true
                 */
                refresh_token_exists: boolean;
            } | null;
            /**
             * @description Whether user can sync Google based on plan
             * @example true
             */
            can_sync_google: boolean;
        };
        /** @description Updated Gmail integration details */
        UpdateIntegrationResponse: {
            /**
             * @description Integration ID
             * @example 123
             */
            id: number;
            /**
             * @description Integration type
             * @example google
             */
            type: string;
            /**
             * @description Account identifier (email address)
             * @example user@gmail.com
             */
            account_identifier: string;
            /**
             * @description Integration status
             * @example connected
             */
            status: string;
            /**
             * @description Whether Gmail is authorized
             * @example true
             */
            authorized_gmail: boolean;
            /**
             * @description Daily email sending limit
             * @example 50
             */
            email_sending_per_day: number;
            /**
             * @description Hourly email sending limit
             * @example 20
             */
            email_sending_per_hour: number;
            /**
             * @description Minimum delay between emails in seconds
             * @example 600
             */
            email_sending_min_delay_seconds: number;
            /**
             * @description Timezone for scheduling
             * @example America/New_York
             */
            timezone: string;
            /**
             * @description Whether this is the default integration for email sending
             * @example true
             */
            email_sending_default: boolean;
        };
        /** @description Gmail integration details */
        IntegrationResponse: {
            /**
             * @description Integration ID
             * @example 123
             */
            id: number;
            /**
             * @description Integration type
             * @example google
             */
            type: string;
            /**
             * Format: email
             * @description Gmail email address
             * @example user@gmail.com
             */
            email: string;
            /**
             * @description Integration status
             * @example connected
             */
            status: string;
            /**
             * @description Whether Gmail is authorized
             * @example true
             */
            authorized_gmail: boolean;
            /**
             * @description Account identifier
             * @example google:123456789012345678
             */
            account_identifier: string;
        };
        /** @description Partner application information */
        AppResponse: {
            /**
             * @description Partner application name
             * @example My App
             */
            title: string;
            /**
             * @description Partner application description
             * @example A description of my app
             */
            description: string | null;
            /**
             * @description Partner application domain
             * @example myapp.example.com
             */
            domain_name: string | null;
            /**
             * @description URL to the partner application logo
             * @example https://example.com/logo.png
             */
            logo: string | null;
            /**
             * @description Partner application public key
             * @example pk_abc123
             */
            public_key: string;
            /**
             * @description Whether the partner application is active
             * @example true
             */
            is_active: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
